version: '3.8'

services:
  php:
    build: ./php
    container_name: php
    environment:
      - MYSQL_HOST='${DB_CONNECTION}'
      - MYSQL_DATABASE='${DB_DATABASE}'
      - MYSQL_USER='${DB_USERNAME}'
      - MYSQL_PASSWORD='${DB_PASSWORD}'
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./src:/var/www
    depends_on:
      - mysql  
    networks:
      - ils-network

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - '${NGINX_PORT}:80'
    volumes:
      - ./src:/var/www
      - ./nginx:/etc/nginx/conf.d 
    depends_on:
      - php 
    networks:
      - ils-network

  mysql:
    image: mysql:8.0.29
    container_name: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD='${DB_ROOTPASSWORD}'
    volumes:
      - mysql_php:/mysql.sql  
    networks:
      - ils-network

  phpmyadmin:
    image: phpmyadmin:latest 
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=1024M
      - MEMORY_LIMIT=1024M
      - MAX_EXECUTION_TIME=300  
    ports:
      - '${PHPMYADMIN_PORT}:80'
    depends_on:
      - mysql 
    networks:
      - ils-network

volumes:
  mysql_php:

networks:
  ils-network:
    driver: bridge